apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: ssd-monitor
spec:
  selector:
    matchLabels:
      app: ssd-monitor
  template:
    metadata:
      labels:
        app: ssd-monitor
    spec:
      nodeSelector: # select nodes with disk=ssd label
        disk: ssd
      containers:
        - name: main
          image: luksa/ssd-monitor
